### Flavours configuration

shell = "bash -c '{}'"

[[items]]
file = "~/.config/bpytop/themes/base16-flavours.theme"
template = "bpytop"
rewrite = true
light = true

[[items]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
subtemplate = "inverted-backgrounds"
start = "### begin base16 scheme"
end = "### end base16 scheme"
rewrite = false
light = false
hook = "killall dunst; swaymsg exec dunst"

[[items]]
file = "~/.config/kitty/current-theme.conf"
template = "kitty"
rewrite = true
hook = "swaymsg reload"
light = false

[[items]]
file = "~/.config/swaylock/config"
template = "swaylock"
subtemplate = "smooth"
start = "### begin base16 scheme"
end = "### end base16 scheme"
rewrite = false
light = true

[[items]]
file = "~/.config/power-menu/fuzzel.ini"
template = "fuzzel"
subtemplate = "smooth"
start = "### begin base16 scheme"
end = "### end base16 scheme"
rewrite = false
light = true

[[items]]
file = "~/.config/fuzzel/fuzzel.ini"
template = "fuzzel"
subtemplate = "smooth"
start = "### begin base16 scheme"
end = "### end base16 scheme"
rewrite = false
light = true

[[items]]
file = "~/.local/share/nvim/site/pack/packer/start/base16-nvim/colors/base16-current.lua"
template = "neovim"
subtemplate = "no-linenr-bg"
rewrite = true
light = true

[[items]]
file = "~/.local/share/nvim/site/pack/packer/start/lualine.nvim/lua/lualine/themes/base16.lua"
template = "lualine"
rewrite = true
light = true

[[items]]
file = "~/.config/sway/config.d/00-color-scheme"
template = "sway"
subtemplate = "colors"
rewrite = true
hook = "swaymsg reload"
light = false

[[items]]
file = "~/.config/waybar/color-scheme.css"
template = "waybar"
rewrite = true
hook = "killall waybar; swaymsg exec GTK_THEME=Adwaita waybar"
light = false

[[items]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true
hook = "import-gsettings"
light = false

[[items]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true
hook = "import-gsettings"

[[items]]
file = "~/.Xdefaults"
template = "xresources"
rewrite = true
hook = "xrdb -merge ~/.Xdefaults"
light = false
